services:
  postgres:
    image: postgres:16-alpine
    container_name: bff_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: chamados_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bff:
    build:
      context: ./bff-chamados
      dockerfile: Dockerfile
    container_name: bff_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/chamados_db?schema=public"
      PORT: 3001
    volumes:
      - ./bff-chamados/uploads:/app/uploads
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend-chamados
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://192.168.3.50:3001"
    depends_on:
      - bff

volumes:
  postgres_data: