services:
  postgres:
    image: postgres:16-alpine
    container_name: bff_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 10

  bff:
    build:
      context: ./bff-chamados
      dockerfile: Dockerfile
    container_name: bff_backend
    restart: always
    ports:
      - "${BFF_PORT}:3001"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
      PORT: ${BFF_PORT}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      MS_CLIENT_ID: ${MS_CLIENT_ID}
      MS_TENANT_ID: ${MS_TENANT_ID}
      MS_URL: ${MS_URL}
    volumes:
      - ./bff-chamados/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend-chamados
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_MS_CLIENT_ID: ${MS_CLIENT_ID}
        NEXT_PUBLIC_MS_TENANT_ID: ${MS_TENANT_ID}
        NEXT_PUBLIC_MS_URL: ${MS_URL}
        NEXT_PUBLIC_REDIRECT_URI: ${REDIRECT_URI}
        ALLOWED_DEV_ORIGINS: ${ALLOWED_DEV_ORIGINS}
    container_name: frontend_app
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_MS_CLIENT_ID: ${MS_CLIENT_ID}
      NEXT_PUBLIC_MS_TENANT_ID: ${MS_TENANT_ID}
      NEXT_PUBLIC_MS_URL: ${MS_URL}
      NEXT_PUBLIC_REDIRECT_URI: ${REDIRECT_URI}
      ALLOWED_DEV_ORIGINS: ${ALLOWED_DEV_ORIGINS}
    depends_on:
      - bff
volumes:
  postgres_data: