# ---------------------------------------------------
# Redireciona o tráfego HTTP (porta 80) para HTTPS
# ---------------------------------------------------
server {
    listen 80;
    server_name spc.online www.spc.online;
    
    location / {
        return 301 https://$host$request_uri;
    }
}

# ---------------------------------------------------
# Bloco HTTPS (porta 443)
# ---------------------------------------------------
server {
    listen 443 ssl;
    server_name spc.online www.spc.online;

    # Certificados Let's Encrypt herdados da máquina host
    ssl_certificate /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;
    include /certs/options-ssl-nginx.conf;
    # ssl_dhparam /certs/ssl-dhparams.pem;

    # Permite uploads de arquivos grandes (Equivalente ao Timeout do Apache)
    client_max_body_size 50M;
    proxy_read_timeout 1800;
    proxy_connect_timeout 1800;
    proxy_send_timeout 1800;

    # ------------------------------------------------------------------
    # Roteamento (Backend SCP e Uploads)
    # ------------------------------------------------------------------
    location /spc/api/ {
        proxy_pass http://bff:3001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /spc/uploads/ {
        proxy_pass http://bff:3001/uploads/;
        proxy_set_header Host $host;
    }

    # ------------------------------------------------------------------
    # Roteamento (Frontend SCP)
    # ------------------------------------------------------------------
    location /spc/ {
        proxy_pass http://frontend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}