# ---------------------------------------------------
# Redireciona o tráfego HTTP (porta 80) para HTTPS
# ---------------------------------------------------
<VirtualHost *:80>
    ServerName spc.online
    ServerAlias www.spc.online
    Redirect permanent / https://spc.online/
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName spc.online
    ServerAlias www.spc.online
    ServerAdmin webmaster@localhost

    # Timeout de 30 minutos para suportar uploads pesados
    ProxyTimeout 1800
    ProxyIOBufferSize 65536

    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # Força a barra no final para evitar erros de roteamento
    RewriteRule ^/spc$ /spc/ [R=301,L]

    # Backend SCP e Uploads (Apontando para o container do backend)
    ProxyPass /spc/api/ http://bff:3001/api/
    ProxyPassReverse /spc/api/ http://bff:3001/api/

    ProxyPass /spc/uploads http://bff:3001/uploads
    ProxyPassReverse /spc/uploads http://bff:3001/uploads

    # Frontend SCP (Apontando para o container do frontend)
    ProxyPass /spc/ http://frontend:3000/
    ProxyPassReverse /spc/ http://frontend:3000/

    # CONFIGURAÇÕES SSL E LOGS
    SSLEngine on
    SSLCertificateFile /certs/fullchain.pem
    SSLCertificateKeyFile /certs/privkey.pem
    Include /certs/options-ssl-apache.conf

    ErrorLog ${APACHE_LOG_DIR}/proxy_ssl_error.log
    CustomLog ${APACHE_LOG_DIR}/proxy_ssl_access.log combined
</VirtualHost>
</IfModule>